version: "3.9"
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql
  rest:
    depends_on:
      - mysqldb
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysqldb
volumes:
  mydb:
